### ISSUE TITLE
the logo is missing!

### ISSUE THREAD

**Issue by vsoch** [earcanal/consent-task#1]
I think maybe just add it to the repo? See the preview here --> https://earcanal.github.io/consent-task/

**Comment by earcanal** [comment]
It's deliberately broken as a cue to check that the content is appropriate for your study.

**Comment by vsoch** [comment]
What do you mean?

**Comment by earcanal** [comment]
Closed by bd96c44.

How to add this commit to the existing PR?

**Comment by vsoch** [comment]
You just push to the branch that the PR is opened for, no additional work needed :)  You don't need to close and re-open, or anything like that.

**Comment by vsoch** [comment]
Also, note that for the other issue (the CI) you need to update your earcanal/experiments repo to be up to date with expfactory/experiments - so there are two updates at hand!
